C:\Users\simog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\huggingface_hub\file_download.py:797: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(






































































































































































































































































































































































































































































































Downloading data: 100%|████████████████████████████████████████| 7.32G/7.32G [16:25<00:00, 7.42MB/s]









































































































































































































































































































































































































































































































































































Generating full split: 16260406 examples [18:36, 14560.43 examples/s]
C:\Users\simog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\datasets\table.py:1421: FutureWarning: promote has been superseded by promote_options='default'.
  table = cls._concat_blocks(blocks, axis=0)
Traceback (most recent call last):
  File "C:\Users\simog\Desktop\Magistrale\Secondo Anno\Primo semestre\DLA\DLAREF\src\main.py", line 107, in <module>
    main()
  File "C:\Users\simog\Desktop\Magistrale\Secondo Anno\Primo semestre\DLA\DLAREF\src\main.py", line 47, in main
    train_loader, val_loader, test_loader = create_data_loaders(preprocessor)
  File "C:\Users\simog\Desktop\Magistrale\Secondo Anno\Primo semestre\DLA\DLAREF\src\main.py", line 11, in create_data_loaders
    (X_train, y_train), (X_val, y_val), (X_test, y_test) = preprocessor.prepare_dataset()
  File "C:\Users\simog\Desktop\Magistrale\Secondo Anno\Primo semestre\DLA\DLAREF\src\data_preprocessing.py", line 39, in prepare_dataset
    reviews = dataset['train']['review_body']
  File "C:\Users\simog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\datasets\dataset_dict.py", line 59, in __getitem__
    return super().__getitem__(k)
KeyError: 'train'